### ISSUE TITLE
NodeBB Crashed

### ISSUE THREAD

**Issue by LetMeDecay** [yariplus/nodebb-plugin-category-sort-by-title#1]
```
28/9 18:54:10 [4542] - error:  TypeError: set.match is not a function
    at Object.Categories.getTopicIds (/home/nodebb/node_modules/nodebb-plugin-category-sort-by-title/library.js:30:15)
    at /home/nodebb/src/categories/topics.js:18:16
    at nextTask (/home/nodebb/node_modules/async/dist/async.js:5297:14)
    at next (/home/nodebb/node_modules/async/dist/async.js:5304:9)
    at /home/nodebb/node_modules/async/dist/async.js:906:16
    at /home/nodebb/node_modules/async/dist/async.js:421:16
    at /home/nodebb/node_modules/async/dist/async.js:2494:9
    at /home/nodebb/node_modules/async/dist/async.js:421:16
    at replenish (/home/nodebb/node_modules/async/dist/async.js:941:25)
    at iterateeCallback (/home/nodebb/node_modules/async/dist/async.js:931:17)
    at /home/nodebb/node_modules/async/dist/async.js:906:16
    at /home/nodebb/node_modules/async/dist/async.js:2491:13
    at /home/nodebb/node_modules/nodebb-plugin-category-sort-by-title/library.js:168:5
    at /home/nodebb/node_modules/async/dist/async.js:421:16
    at next (/home/nodebb/node_modules/async/dist/async.js:5302:29)
    at /home/nodebb/node_modules/async/dist/async.js:906:16
    at /home/nodebb/src/user/settings.js:123:5
    at nextTask (/home/nodebb/node_modules/async/dist/async.js:5297:14)
    at next (/home/nodebb/node_modules/async/dist/async.js:5304:9)
    at /home/nodebb/node_modules/async/dist/async.js:906:16
    at /home/nodebb/node_modules/async/dist/async.js:421:16
    at /home/nodebb/node_modules/async/dist/async.js:2494:9
```

**Comment by yariplus** [comment]
Thanks, will fix asap.
